### Data Analysis


* Data analysis is the process of obtaining raw data and subsequently converting it into information,useful for decision making by the users


### Data analysis

* Analysing Numerical data by using Numpy
* Tabular data using Pandas
* Visualization using Matplotlib

### Data
* Data is facts and statistics collected together for analysis or reference

### Data Collection

* Primary data : Data that is collected by himself/herself ex: Interviews,experiments etc
* Secondary data Collection: Data is generated by someone else earlier  ex: Websites, Books

### Types data:

* Structured data: rows/columns i.e table  ex: excel,.csv
* Unstructured data: audio,vidoe,pictures etc
* Semi structured data: json,html etc

In [1]:
l=[10,20,30,40]

# 100

l+100  # element wise operation not possible in list

TypeError: can only concatenate list (not "int") to list

###  advantages of numpy array over list

* consumes less memory
* fast compared with python list
* Convinient to use

### Numpy -  Numerical python

* It is a open source python library
* It is used for scientific computing and works with arrays
* Numpy provides high level functioning tools to work with arrays
* Using numpy we can perform mathematical and logical opertaions on arrays
* It also has functions in the domain of Linear algebra,fourier transforms and matrices

In [2]:
import numpy as np

In [3]:
# Creating 1 dimensional array

l=[90,8,67,56]
a=np.array(l)
a

array([90,  8, 67, 56])

In [4]:
type(a)

numpy.ndarray

In [5]:
b=a+100
b

array([190, 108, 167, 156])

In [6]:
print(a.ndim)  # no of dimensions
print(a.dtype)  # data type of items
print(a.shape)  # shape
print(a.size)   # no of elements inside array
print(a.itemsize)  # each item size

1
int32
(4,)
4
4

In [7]:
a1=np.array([10,20,30,40],dtype="complex")
a1

array([10.+0.j, 20.+0.j, 30.+0.j, 40.+0.j])

In [9]:
a2=np.array([11,12,13],ndmin=2)
print(a2)
print(a2.ndim)

[[11 12 13]]
2

In [10]:
b=np.array([10,90,76,45,34,23])
b

array([10, 90, 76, 45, 34, 23])

In [11]:
print(b.sum())
print(b.max())
print(b.min())
print(b.argmax())   # index of max value
print(b.argmin())

278
90
10
1
0

In [14]:
# range() and arange()

a=np.array(range(1,101))
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
# create an array with even numbers in the range of 100

even=np.array(range(2,101,2))
even

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [16]:
# array with odd numbers in the range of 100 to 200

In [17]:
# arange() -> belongs to numpy

a=np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [21]:
a=np.arange(25)
print(a)
print(a.ndim)

# converting 1D into 2D array

b=a.reshape(5,5)
print(b)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
1
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
2

In [23]:
a=np.arange(24)
b=a.reshape(6,4)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

* linspace() -> returns no of spaces evenly w.r.to given interval

In [24]:
a=np.linspace(1,20,5)
a

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [25]:
b=np.linspace(1,5)
b

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

### Array Initialization

* np.ones() ->  creates an array with given shape and type with ones

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.ones([2,2],dtype=int)

array([[1, 1],
       [1, 1]])

In [29]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [30]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [31]:
np.zeros([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

In [33]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
a=np.full([2,2],60)
a

array([[60, 60],
       [60, 60]])

In [ ]:
# create an array with 3 rows and 4 columns with array value as 1
# create an 1D aray with 36 elements and reshape it as 2D array with 6 rows and 6 columns

* eye() -> create 2 D array with 1's on diagonal and 0's elsewhere

In [5]:
import numpy as np
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [6]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# 3,4,5

np.diag([3,4,5])

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [9]:
np.empty(3)

array([1., 1., 1.])

In [10]:
np.empty(9)

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [11]:
np.empty([2,2])

array([[1., 0.],
       [0., 1.]])

In [16]:
# accessing 1D array elements

a=np.array([12,34,55,78])
print(a)
print(a[0])
print(a[1]+a[2])     
print(a[-1])
print(a[::-1])

[12 34 55 78]
12
89
78
[78 55 34 12]

In [17]:
# Creating 2 Dimensional array

l1=[10,20,30,40]
l2=[50,60,70,80]
b=np.array([l1,l2])
print(b)
print(b.ndim)

[[10 20 30 40]
 [50 60 70 80]]
2

In [20]:
# Accessing 2D array elements

print(b[0,0])  # row index,col index
print(b[1,2])
# 60
print(b[1,1])

10
70
60

In [22]:
# creating 3D array

c=np.array([ [[10,20],[30,40]],
          [[50,60],[70,80]] ])
print(c)
print(c.ndim)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
3

In [23]:
c[0]

array([[10, 20],
       [30, 40]])

In [24]:
c[1]

array([[50, 60],
       [70, 80]])

In [26]:
print(c[0,0,1])

20

In [28]:
# random
np.random.random()   # random value b/w 0 to 1

0.44607306780987943

In [29]:
# randint()

np.random.randint(700)

384

In [30]:
np.random.randint(10,100,5)

array([29, 45, 95, 92, 71])

In [33]:
a=np.random.randint(100,200,10)
a

array([197, 190, 117, 109, 198, 177, 196, 195, 170, 126])

In [34]:
# fancy indexing or boolean indexing
a>150

array([ True,  True, False, False,  True,  True,  True,  True,  True,
       False])

In [35]:
a[a>150]

array([197, 190, 198, 177, 196, 195, 170])

In [36]:
# slicing

a=np.random.randint(1,10,5)
a

array([5, 6, 9, 7, 7])

In [37]:
a[:3]

array([5, 6, 9])

In [38]:
a[::-1]

array([7, 7, 9, 6, 5])

In [39]:
a[::2]

array([5, 9, 7])

In [40]:
a[1::2]

array([6, 7])

In [41]:
a=np.arange(32)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [42]:
a.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [43]:
a.reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [44]:
a.reshape(4,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [45]:
a.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [46]:
a.reshape(8,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [47]:
def grt(a,b):
    if a>b:
        return a
    else:
        return b
grt(87,909)

909

In [48]:
grt([10,2,340],[90,89,87])

[90, 89, 87]

In [50]:
vgrt=np.vectorize(grt)
vgrt([10,2,340],[90,89,87])

array([ 90,  89, 340])

In [51]:
# stacking 

a=np.array([1,2,3])
b=np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [52]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
# mathematical operations

a1=np.arange(1,4)
a2=np.array([4,5,6])
a1

array([1, 2, 3])

In [54]:
a2

array([4, 5, 6])

In [56]:
print(a1+a2)
print(a1-a2)
print(a1*a2)    # normal multiplication
print(a1/a2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]

In [61]:
a=np.array([[1,2],[3,4]])
b=np.identity(2)
print(a)
print(b)
np.dot(a,b)  # matrix multiplication

[[1 2]
 [3 4]]
[[1. 0.]
 [0. 1.]]

array([[1., 2.],
       [3., 4.]])

In [57]:
# mean -> sum of elements/no of elements
# median -> middle value of a sorted array
# mode -> most repeated value

In [63]:
a=np.array([10,50,20,40,30])
print(a.mean())
print(np.mean(a))
print(np.median(a))

30.0
30.0
30.0

### Pandas

* Pandas stands for python data analysis library
* It is free and open source
* It is an excellent tool for Data Processing and analyzing real world data

### Pandas Data structures

* 1. Series : Used to create 1 dimensional array with named index eg:single column in an excel sheet
* 2. Data Frame: Used to create 2 Dimensional array with row index and column index eg:table in an excel sheet

In [66]:
import pandas as pd

In [67]:
pd.__version__

'1.4.4'

In [72]:
# creating series using list
l=[10,20,30,40,50]
s=pd.Series(l)
print(s)
print(type(s))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>

In [71]:
# changing the index
s.index=['a','b','c','d','e']
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [74]:
s=pd.Series([90,'hello',70.8],index=['x','y','z'])
s

x       90
y    hello
z     70.8
dtype: object

In [75]:
# creating series by using numpy array

a=np.array([90,87,56])
s1=pd.Series(a)
s1

0    90
1    87
2    56
dtype: int32

In [76]:
# creating series by using tuple

s=pd.Series((100,294,45,65))
s

0    100
1    294
2     45
3     65
dtype: int64

In [77]:
# creating series by using dictionary

d={"stu1":90,"stu2":86,"stu3":88}
s=pd.Series(d)
s

stu1    90
stu2    86
stu3    88
dtype: int64

In [78]:
# accessing series

s["stu1"]

90

In [79]:
s["stu3"]

88